apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-writer
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces"]
    verbs: ["create", "delete", "update", "get", "list", "watch",]